WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "train.py", line 19, in <module>
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    import lavis.tasks as tasks
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/__init__.py", line 15, in <module>
    import lavis.tasks as tasks
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/__init__.py", line 15, in <module>
    from lavis.datasets.builders import *
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/datasets/builders/__init__.py", line 8, in <module>
    from lavis.datasets.builders import *
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/datasets/builders/__init__.py", line 8, in <module>
    from lavis.datasets.builders.base_dataset_builder import load_dataset_config
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/datasets/builders/base_dataset_builder.py", line 17, in <module>
    from lavis.datasets.builders.base_dataset_builder import load_dataset_config
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/datasets/builders/base_dataset_builder.py", line 17, in <module>
    from lavis.datasets.data_utils import extract_archive
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/datasets/data_utils.py", line 20, in <module>
    from lavis.datasets.data_utils import extract_archive
  File "/home/atuin/g102ea/g102ea22/mr-Audio/lavis/datasets/data_utils.py", line 20, in <module>
    import torchaudio
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torchaudio/__init__.py", line 2, in <module>
    import torchaudio
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torchaudio/_extension/__init__.py", line 42, in <module>
    from . import _extension  # noqa  # usort: skip
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torchaudio/_extension/__init__.py", line 42, in <module>
    _check_cuda_version()
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torchaudio/_extension/utils.py", line 175, in _check_cuda_version
    _check_cuda_version()
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torchaudio/_extension/utils.py", line 175, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 11.8. Please install the TorchAudio version that matches your PyTorch version.
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 11.8. Please install the TorchAudio version that matches your PyTorch version.
E1215 12:38:53.197218 23220707812864 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 403765) of binary: /home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/bin/python
Traceback (most recent call last):
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/atuin/g102ea/g102ea22/software/private/conda/envs/mrBlip/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-15_12:38:53
  host      : a0605.nhr.fau.de
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 403766)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-15_12:38:53
  host      : a0605.nhr.fau.de
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 403765)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
